name: Build nxdumptool `rewrite` tests

on:
  push:
    branches: [ rewrite ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Building rewrite nxdumptool...
        run: |
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          export COMMIT="$(git rev-parse --short HEAD)"
          echo $COMMIT
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo dkp-pacman -Syu --noconfirm
          cd $GITHUB_WORKSPACE/libs/libusbhsfs/liblwext4
          dkp-makepkg -si --noconfirm
          cd $GITHUB_WORKSPACE/libs/libusbhsfs/libntfs-3g
          dkp-makepkg -si --noconfirm
          cd $GITHUB_WORKSPACE
          chmod +x ./build.sh
          ./build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: nxdt-rewrite-${{ env.commit }}
          path: \*.7z
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
