name: Build nxdumptool `rewrite` tests

on:
  push:
    branches: [ rewrite ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Updating repos and install dkp-toolchain-vars...
        run: |
          sudo apt-get update
          sudo apt-get upgrade patch -y
          chmod 777 -R $GITHUB_WORKSPACE
          sudo dkp-pacman --noconfirm -U $GITHUB_WORKSPACE/libs/dkp-toolchain-vars/dkp-toolchain-vars-1.0.0-2-any.pkg.tar.xz

      - name: Double check variables to make sure everything's properly set.
        run: |
          echo "COMMIT="$(git rev-parse --short HEAD)"\nDEVKITPRO=/opt/devkitpro\nDEVKITARM=/opt/devkitpro/devkitARM\nDEVKITPPC=/opt/devkitpro/devkitPPC" >> $GITHUB_ENV
          echo $COMMIT $DEVKITPRO $DEVKITARM $DEVKITPPC

      - name: useradd to try and force makepkg to work
        run: |
          useradd nxdt-build

      - name: Building libusbhsfs - liblwext4...
        run: |
          cd $GITHUB_WORKSPACE/libs/libusbhsfs/liblwext4
          sudo -n chmod 777 -R $GITHUB_WORKSPACE/libs/libusbhsfs
          sudo -u nxdt-build -n dkp-makepkg -i --noconfirm

      - name: Building libusbhsfs - libntfs-3g...
        run: |
          cd $GITHUB_WORKSPACE/libs/libusbhsfs/libntfs-3g
          sudo -n chmod 777 -R $GITHUB_WORKSPACE/libs/libusbhsfs/
          dkp-makepkg -si --noconfirm

      - name: Building nxdumptool...
        run: |
          export 
          echo $COMMIT
          cd $GITHUB_WORKSPACE
          chmod +x ./build.sh
          ./build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: nxdt-rewrite-${{ env.commit }}
          path: \*.7z
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
