name: Build nxdumptool 'rewrite' tests

on:
  push:
    branches: [ rewrite ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Updating repos, install dkp-toolchain-vars, and set permissions...
        run: |
          sudo apt-get update ; sudo apt-get upgrade -y patch fakeroot p7zip-full
          sudo -n dkp-pacman --noconfirm -U $GITHUB_WORKSPACE/libs/dkp-toolchain-vars/dkp-toolchain-vars-1.0.0-2-any.pkg.tar.xz
          useradd nxdt-build
          chmod 777 -R $GITHUB_WORKSPACE

#     - name: Building nxdumptool...
#        run: |
#          cd $GITHUB_WORKSPACE
#          # ./build.sh
#          touch nxdumptool-rewrite_poc_$COMMIT.7z nxdumptool-rewrite_poc_$COMMIT-Debug_ELFs.7z
#          echo nxdumptool-rewrite_poc_$COMMIT.7z nxdumptool-rewrite_poc_$COMMIT-Debug_ELFs.7z
#          ls nxdumptool-rewrite_poc_$COMMIT.7z nxdumptool-rewrite_poc_$COMMIT-Debug_ELFs.7z

#      - name: nxdumptool rewrite (NRO)
#      - uses: actions/upload-artifact@v2
#        with:
#          name: nxdumptool rewrite (NRO) - $COMMIT
#          path: nxdumptool-rewrite_poc_$COMMIT.7z
#          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to 'warn'

#       - name: nxdumptool rewrite (Debug ELFs)
#       - uses: actions/upload-artifact@v2
#         with:
#           name: nxdumptool rewrite (Debug ELFs) - $COMMIT
#           path: nxdumptool-rewrite_poc_$COMMIT-Debug_ELFs.7z
#           if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to 'warn'