name: Build nxdumptool `rewrite` tests

on:
  push:
    branches: [ rewrite ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
#      options: --user 1001
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: echo "I am $(whoami)"
      - name: Updating repos...
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          alias dkp-makepkg=makepkg
          chmod 777 -R $GITHUB_WORKSPACE

      - name: useradd to try and force makepkg to work
        run: |
          useradd nxdt-build

      - name: Building libusbhsfs - liblwext4...
        run: |
          whoami
          cd $GITHUB_WORKSPACE/libs/libusbhsfs/liblwext4
          sudo -n chmod 777 -R $GITHUB_WORKSPACE/libs/libusbhsfs
          sudo -u nxdt-build -n whoami
          sudo -u nxdt-build -n dkp-makepkg -si --noconfirm

      - name: Building libusbhsfs - libntfs-3g...
        run: |
          cd $GITHUB_WORKSPACE/libs/libusbhsfs/libntfs-3g
          sudo -n chmod 777 -R $GITHUB_WORKSPACE/libs/libusbhsfs/
          dkp-makepkg -si --noconfirm

      - name: Building nxdumptool...
        run: |
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          export COMMIT="$(git rev-parse --short HEAD)"
          echo $COMMIT
          cd $GITHUB_WORKSPACE
          chmod +x ./build.sh
          ./build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: nxdt-rewrite-${{ env.commit }}
          path: \*.7z
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
