name: Build nxdumptool `rewrite` tests

on:
  push:
    branches: [ rewrite ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Updating repos and install dkp-toolchain-vars...
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y patch fakeroot p7zip-full
          chmod 777 -R $GITHUB_WORKSPACE
          sudo -n dkp-pacman --noconfirm -U $GITHUB_WORKSPACE/libs/dkp-toolchain-vars/dkp-toolchain-vars-1.0.0-2-any.pkg.tar.xz

      - name: Double check variables to make sure everything's properly set.
        run: |
          export COMMIT="$(git rev-parse --short HEAD)" DEVKITPRO=/opt/devkitpro DEVKITARM=/opt/devkitpro/devkitARM DEVKITPPC=/opt/devkitpro/devkitPPC
          echo commit="$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo $COMMIT $DEVKITPRO $DEVKITARM $DEVKITPPC

      - name: useradd to try and force makepkg to work
        run: |
          useradd nxdt-build

      - name: Building libusbhsfs - liblwext4...
        run: |
          cd $GITHUB_WORKSPACE/libs/libusbhsfs/liblwext4
          sudo chmod 777 -R $GITHUB_WORKSPACE/libs/libusbhsfs
          sudo -u nxdt-build -n COMMIT="$(git rev-parse --short HEAD)" DEVKITPRO=/opt/devkitpro DEVKITARM=/opt/devkitpro/devkitARM DEVKITPPC=/opt/devkitpro/devkitPPC dkp-makepkg
          sudo dkp-pacman -U switch-lwext4*.tar.xz --noconfirm

      - name: Building libusbhsfs - libntfs-3g...
        run: |
          cd $GITHUB_WORKSPACE/libs/libusbhsfs/libntfs-3g
          sudo -u nxdt-build -n COMMIT="$(git rev-parse --short HEAD)" DEVKITPRO=/opt/devkitpro DEVKITARM=/opt/devkitpro/devkitARM DEVKITPPC=/opt/devkitpro/devkitPPC dkp-makepkg
          sudo dkp-pacman -U switch-libntfs-3g*.tar.xz --noconfirm

      - name: Building nxdumptool...
        run: |
          echo $COMMIT
          cd $GITHUB_WORKSPACE
          chmod +x ./build.sh
          ./build.sh
          ls nxdumptool-rewrite_poc_$COMMIT.7z nxdumptool-rewrite_poc_$COMMIT-Debug_ELFs.7z

      - uses: actions/upload-artifact@v2
        with:
          name: nxdt-rewrite-poc-${{ env.commit }}-nro
          path: nxdumptool-rewrite_poc_${{ env.commit }}.7z
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

        with:
          name: nxdt-rewrite-poc-${{ env.commit }}-Debug_ELFs
          path: nxdumptool-rewrite_poc_${{ env.commit }}-Debug_ELFs.7z
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
